# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


    apikey_authenticator:
        class:  AppBundle\Security\ApiKeyAuthenticator
        public: false
        arguments: ["@security.http_utils"]

    api_key_user_provider:
        class: AppBundle\Security\UserProvider
        arguments: ["@doctrine.orm.default_entity_manager"]
